name: ACTIONet
on:
  push:
    branches:
      - '**release**'
jobs:
  main:
    runs-on: self-hosted
    timeout-minutes: 3000
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      - name: Set up Docker Buildx
        if: hashFiles('/home/ubuntu/.docker/cli-plugins/docker-buildx') == ''
        id: buildx
        uses: docker/setup-buildx-action@v1
        with:
          version: latest
          driver-opts: network=host
      - name: Login to DockerHub Registry
        run: echo ${{ secrets.DOCKERHUB_TOKEN }} | docker login -u ${{ secrets.DOCKERHUB_USERNAME }} --password-stdin
      - name: Login to ECR
        uses: docker/login-action@v1
        with:
          registry: '${{ secrets.AWS_REGISTRY_URL }}'
          username: '${{ secrets.AWS_ACCESS_KEY_ID }}'
          password: '${{ secrets.AWS_SECRET_ACCESS_KEY }}'
      - name: Build and push latest docker
        uses: docker/build-push-action@v2
        with:
          context: ./docker@master
          file: ./docker/Dockerfile@master
          push: true|
            GITHUB_TOKEN=${{ secrets.GITHUB_TOKEN }}
          build-args: |
            PARENT_DOCKER=shmohammadi86/genomics:latest
            GITHUB_PAT=${{ secrets.GITHUB_TOKEN }}
          tags: |
            shmohammadi86/genomics:actionet
            shmohammadi86/genomics:latest
            ${{ secrets.AWS_REGISTRY_URL }}/genomics:actionet
            ${{ secrets.AWS_REGISTRY_URL }}/genomics:latest
